<div class="container">
    <form method='POST' action="/magento2/exampleadminnewpage/helloworld/save">
        <div class="form-group">
            <label for="name">First Name</label>
            <input type="text" class="form-control" id="firstname" placeholder="Enter your first name" name="firstname" </div> <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" id="email" placeholder="Enter your email" name="email" </div> <div class="form-group">
            <label for="lastname">Last Name</label>
            <input type="text" class="form-control" id="lastname" placeholder="Enter your last name" name="lastname" </div> <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" placeholder="Enter your password" name="password" </div> <br> <button type="submit" class="btn btn-primary" name="submitbtn">Submit</button>
    </form>
</div>
